#ifndef UPLOAD_SAT_DTP_SERVER_H
#define UPLOAD_SAT_DTP_SERVER_H


#define INDECES_PACKET_SIZE 196
#define INDECES_PORT 13


#define UPLOAD_SAT_OBSERVATION_AMOUNT_REQUEST 0
#define UPLOAD_SAT_DTP_OBSERVATION_META_REQUEST 1

#endif
